#!/bin/bash
# ================================ HEADER =====================================
# Author:       Loic Delineau
# Date:         04/11/2024
# Licence:     	GNU-GPLv3 
# File:        	install_raspberry 
# Platform :    Raspberry Pi 5 running Ubuntu 24.04 bare metal
# Description:	Installs all necessary packages for microver.ch on new Raspi5 

# ======================= USER SYSTEM IDENTIFICATION ==========================
# Checking if the script is being sourced
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
	echo ""
	echo "You didn't source the script, please restart it with:"
	echo ". ./install_raspberry"
	echo ""
	exit
else
    echo "Script is being sourced"
fi


# =========================== SCRIPT EXECUTION ================================
# Initial Package Update & Upgrade
echo "Starting the Raspberry Pi 5 Setup Procedure for microver.ch"
echo "--> This script will take 20 minutes to finish" # time it!

# Waiting to let user read
echo ""
sleep 2
echo "."
sleep 2
echo "."
sleep 2
echo "."
sleep 2
echo ""

# Updating packages using apt
sudo apt-get update && sudo apt-get upgrade -y

# Installing basic programs one can't live without
sudo apt install vim -y
sudo apt install htop -y
sudo apt install neofetch -y
sudo apt install git -y
sudo apt install build-essential -y
sudo apt install python3-gpiozero -y

# Installing ROS2 Jazzy Jalisco -----------------------------------------------
# https://docs.ros.org/en/jazzy/Installation/Ubuntu-Install-Debs.html

locale  # check for UTF-8

sudo apt update && sudo apt install locales -y
sudo locale-gen en_US en_US.UTF-8 
sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 
export LANG=en_US.UTF-8

locale  # verify settings

# Adding sources
sudo apt install software-properties-common -y
sudo add-apt-repository universe -y

# Adding ROS2 GPG key
sudo apt update && sudo apt install curl -y
sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg

# Adding Repo to sources list
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null

# Installing ROS dev tools
sudo apt update && sudo apt install ros-dev-tools -y


# Installing ROS2
sudo apt update && sudo apt upgrade -y
sudo apt install ros-jazzy-desktop -y # GUI version of ROS2

# Sourcing ROS & adding it to bashrc
source /opt/ros/jazzy/setup.bash
echo "source /opt/ros/jazzy/setup.bash" >> ~/.bashrc

# ========================== Closing Messages ================================= 
sudo apt update && sudo apt upgrade -y

echo ""
echo "The script is about to launch an example talker and listener in new tabs"
echo ""
echo "Details of this script are documented here:"
echo "https://docs.microver.ch"
echo ""
echo "Lovingly built by:"
echo "            _                                          _     "
echo "           (_)                                        | |    "
echo " _ __ ___   _   ___  _ __  ___ __   __ ___  _ __  ___ | |__  "
echo "| '_ \` _ \\ | | / __|| '__|/ _ \\  \\ / // _ \\| '__|/ __|| '_ \\ "
echo "| | | | | || || (__ | |  | (_) |\ V /|  __/| | _| (__ | | | |"
echo "|_| |_| |_||_| \___||_|   \___/  \_/  \___||_|(_)\___||_| |_|"
echo ""

sleep 3

# Running example tabs as talkers and listeners
gnome-terminal --tab -- bash -c "ros2 run demo_nodes_cpp talker; exec bash"
gnome-terminal --tab -- bash -c "ros2 run demo_nodes_py listener; exec bash"

