#!/bin/bash

# Installing it all here:
# /etc/systemd/system/networking.service.d/reduce-timeout.conf

cd /etc/systemd/system
sudo mkdir networking.service.d
cd ./networking.service.d
sudo touch /reduce-timeout.conf

echo "[Service]" | sudo tee -a reduce-timeout.conf
echo "TimeoutStartSec=1" | sudo tee -a reduce-timeout.conf

